
print('"exercicio M1S1"')
print('                ')
print('1º expressão')
resultado1 = (10 + 20 * 30)
print("10+20x30")
print("resposta da primeira expressão")
print(resultado1)
print('##########')
print('  ')
print('2º expressão')
resultado2 = ((4**2)/30)
print('4²/ 30')
print('resposta da segunda expressão')
print(resultado2)
print('##########')
print('  ')
print('3º expressão')
print('(9**4) + 2 x 6 - 1')
resultado3 = ((9**4+2)*6-1)
print('resposta da terceira expressão')
print(resultado3)
print('##########')
print('  ')
print("4º expressão")
print('10 % 3 * 10 ** 2 + 1 - 10 * 4 / 2')
resultado4 = ((10%3) * 10**2 + 1 - (10 * 4)/2)
print("resposta da 4ª expressão")
print(int(resultado4))
print(" ")
print(('eu to programando porraaaaaaaa!!!!').upper)
